### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by antonijask** [radicleart/brightblock-oam#14]
Please make Links in Footer aligned with Header main navigation style:

16pt
same padding
400 font weight, both Header and Footer
(atm header has 300 font weight)

remove hearth from the footer

![footer](https://user-images.githubusercontent.com/47831018/54362611-834eca00-4669-11e9-9d46-26d8c4a0cf26.jpg)

**Comment by radicleart** [comment]
God - I hope this is right - can you check.

I set font-size to 1.3em as this looked close to 16pt
