### ISSUE TITLE
Login Button

### ISSUE THREAD

**Issue by antonijask** [radicleart/brightblock-oam#16]
Please change Login into Login with Blockstack.

This way we lose 1 step.

![Login_Button](https://user-images.githubusercontent.com/47831018/54420354-13445080-470a-11e9-9570-07bed65c2f12.jpg)

**Comment by radicleart** [comment]
@antonijask its block capitals - so just checking your happy..

![Screen Shot 2019-03-15 at 09 43 18](https://user-images.githubusercontent.com/4384929/54422636-d88ce900-4706-11e9-9bd2-30524a7a7463.png)

**Comment by radicleart** [comment]
Or I can change from uppercase to capitalize like this?

![Screen Shot 2019-03-15 at 09 45 19](https://user-images.githubusercontent.com/4384929/54422760-1427b300-4707-11e9-9a84-3892bbbba1be.png)

**Comment by antonijask** [comment]
Yes, please this way is better :)

<3
