### ISSUE TITLE
Artists Page

### ISSUE THREAD

**Issue by antonijask** [radicleart/brightblock-oam#28]
UI changeproposal for the https://radicle.art/artists
![Artists-List_Page](https://user-images.githubusercontent.com/47831018/57225376-7d8fb800-700c-11e9-9ab9-ab554db0152f.png)

Instead of having images proposing an alphabetic order of names

**Comment by radicleart** [comment]
Leaving this for FED especially as we don't have enough artists to make this layout work right now.
