### ISSUE TITLE
Register Ownership - transaction failed

### ISSUE THREAD

**Issue by antonijask** [radicleart/brightblock-oam#29]
I have issue Registering Artwork Ownership. 
Any ideas how to solve this?

<img width="1155" alt="Screenshot 2019-05-16 at 12 34 13" src="https://user-images.githubusercontent.com/47831018/57847689-59d02d00-77d7-11e9-9300-b8643e913161.png">

**Comment by radicleart** [comment]
Fixed. Added more detailed logging
