### ISSUE TITLE
Register Ownership - UX improvements

### ISSUE THREAD

**Issue by antonijask** [radicleart/brightblock-oam#30]
All buttons should have the same copy
“REGISTER OWNERSHIP”

it's confusing atm:
we have "REGISTER" button, title "REGISTER OWNERSHIP", and then confirmation “REGISTER BITCOIN”.

We should be consistent there, let's just keep "REGISTER OWNERSHIP".

Or:

REGISTER
REGISTER OWNERSHIP
CONFIRM

**Comment by radicleart** [comment]
Made more consistent
